### ISSUE TITLE
Issue to run DIME_VQA.ipynb

### ISSUE THREAD

**Issue by robi56** [lvyiwei1/DIME#1]
I am facing trouble to run the DIME_VQA.ipynb

The output of the second cell is below  but the cell is blank 
```
Cloning into 'multimodal_analysis'...
remote: Enumerating objects: 393, done.
remote: Counting objects: 100% (393/393), done.
remote: Compressing objects: 100% (302/302), done.
remote: Total 393 (delta 187), reused 150 (delta 52), pack-reused 0
Receiving objects: 100% (393/393), 2.95 MiB | 10.01 MiB/s, done.
Resolving deltas: 100% (187/187), done.
```

**Comment by lvyiwei1** [comment]
Thank you for your interest in our work!

This is just a saved output from an older version of the script and it does not affect the running of the current script. Feel free to just ignore this blank cell and its output
